/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;

//import com.sun.corba.se.pept.transport.Connection;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Harsh
 */
public class AddBook extends javax.swing.JFrame {
       
    /**
     * Creates new form AddBook
     */
    String b_id,b_name,b_author,b_publication,b_edition ;
    String book_name , name_capital;
    int copies;
    private int mouseX;
    private int mouseY;
    private Color redColor = new Color(204,51,0);    
    PreparedStatement ps;
    Connection con ;
    ResultSet rs;
     
    
   
   
    public AddBook() {
        initComponents();
        
        JTableHeader Theader = table.getTableHeader();
        Theader.setOpaque(false);
        Theader.setBackground(new Color(23,34,55));
        Theader.setForeground(new Color(255,255,255)); 
        Theader.setFont(new Font("Tahome " ,Font.BOLD, 20));
//        ****************************************Adding records from db to the table****************************
        try
        { 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
            String sql = "SELECT * FROM tp ";
            ps = con.prepareStatement(sql);
            
            rs = ps.executeQuery ();
          DefaultTableModel tblModel = (DefaultTableModel)table.getModel();
          tblModel.setRowCount(0);
            while(rs.next())
            {
                b_id  = rs.getString("book_id");
                b_name = rs.getString("name");
                b_author = rs.getString("author_name");
                b_edition = rs.getString("edition");
                b_publication =  rs.getString("publisher");
                
                  String tbdata[]={b_id,b_name,b_author,b_edition,b_publication};
    
            tblModel.addRow(tbdata);

            } 

        }
        catch(Exception e)
        {
                e.getMessage();
        } 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
            
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbl_bookid = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_edition = new javax.swing.JLabel();
        lbl_publi = new javax.swing.JLabel();
        tf_addId = new javax.swing.JTextField();
        tf_addName = new javax.swing.JTextField();
        tf_addAuthor = new javax.swing.JTextField();
        tf_addEdition = new javax.swing.JTextField();
        tf_addPublication = new javax.swing.JTextField();
        lbl_bookName = new javax.swing.JLabel();
        lbl_copies = new javax.swing.JLabel();
        tf_copies = new javax.swing.JTextField();
        Lbl_addBooks = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_viewBook = new javax.swing.JLabel();
        lbl_viewUser = new javax.swing.JLabel();
        lbl_viewIssue = new javax.swing.JLabel();
        lbl_deleteBook = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        lbl_viewReturned = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbl_bookid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_bookid.setForeground(new java.awt.Color(102, 102, 102));
        lbl_bookid.setText("Book Id :");

        lbl_author.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(102, 102, 102));
        lbl_author.setText("Author :");

        lbl_edition.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_edition.setForeground(new java.awt.Color(102, 102, 102));
        lbl_edition.setText("Edition :");

        lbl_publi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_publi.setForeground(new java.awt.Color(102, 102, 102));
        lbl_publi.setText("Publications :");

        tf_addId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_addId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_addId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_addIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_addIdFocusLost(evt);
            }
        });

        tf_addName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_addName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_addName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_addNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_addNameFocusLost(evt);
            }
        });
        tf_addName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_addNameActionPerformed(evt);
            }
        });

        tf_addAuthor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_addAuthor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_addAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_addAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_addAuthorFocusLost(evt);
            }
        });

        tf_addEdition.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_addEdition.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_addEdition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_addEditionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_addEditionFocusLost(evt);
            }
        });

        tf_addPublication.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_addPublication.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_addPublication.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_addPublicationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_addPublicationFocusLost(evt);
            }
        });

        lbl_bookName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(102, 102, 102));
        lbl_bookName.setText("Book Name :");

        lbl_copies.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_copies.setForeground(new java.awt.Color(102, 102, 102));
        lbl_copies.setText("No of Copies Available :");

        tf_copies.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tf_copies.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_copies.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_copiesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_copiesFocusLost(evt);
            }
        });
        tf_copies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_copiesActionPerformed(evt);
            }
        });

        Lbl_addBooks.setBackground(new java.awt.Color(113, 189, 255));
        Lbl_addBooks.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        Lbl_addBooks.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_addBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_addBooks.setText("Add Book");
        Lbl_addBooks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lbl_addBooks.setOpaque(true);
        Lbl_addBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_addBooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lbl_addBooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lbl_addBooksMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_bookName)
                    .addComponent(lbl_bookid)
                    .addComponent(lbl_author))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_addId, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(tf_addName)
                    .addComponent(tf_addAuthor))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_publi)
                    .addComponent(lbl_copies)
                    .addComponent(lbl_edition))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_addPublication)
                    .addComponent(tf_addEdition)
                    .addComponent(tf_copies, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_addBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(517, 517, 517))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lbl_bookid))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lbl_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(tf_addId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_addName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_bookName)
                                    .addComponent(lbl_publi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_addPublication, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_author, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_copies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tf_addAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_addEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_copies, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addComponent(Lbl_addBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 1240, 350));

        jPanel5.setBackground(new java.awt.Color(122, 125, 128));
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 68));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Books Available");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 1240, 60));

        jPanel3.setBackground(new java.awt.Color(122, 125, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Books To Library");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 1240, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Id", "Book Name", "Author Name", "Edition", "Publication"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusable(false);
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(30);
        table.setSelectionBackground(new java.awt.Color(153, 153, 153));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(100);
            table.getColumnModel().getColumn(0).setPreferredWidth(100);
            table.getColumnModel().getColumn(0).setMaxWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("All CopyRights Reserved /University");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 1240, 370));

        jPanel6.setBackground(new java.awt.Color(58, 63, 67));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 850));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Atharva Dhadke\\Desktop\\Java Project Images\\final admin .png")); // NOI18N
        jLabel19.setText("jLabel19");

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("MR Admin");
        jLabel20.setOpaque(true);

        lbl_viewBook.setBackground(new java.awt.Color(58, 63, 67));
        lbl_viewBook.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_viewBook.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_viewBook.setText("View Books");
        lbl_viewBook.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_viewBook.setOpaque(true);
        lbl_viewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewBookMouseExited(evt);
            }
        });

        lbl_viewUser.setBackground(new java.awt.Color(58, 63, 67));
        lbl_viewUser.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_viewUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_viewUser.setText("View User");
        lbl_viewUser.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_viewUser.setOpaque(true);
        lbl_viewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewUserMouseExited(evt);
            }
        });

        lbl_viewIssue.setBackground(new java.awt.Color(58, 63, 67));
        lbl_viewIssue.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_viewIssue.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewIssue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_viewIssue.setText("View Issued Books");
        lbl_viewIssue.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_viewIssue.setOpaque(true);
        lbl_viewIssue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewIssueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewIssueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewIssueMouseExited(evt);
            }
        });

        lbl_deleteBook.setBackground(new java.awt.Color(58, 63, 67));
        lbl_deleteBook.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_deleteBook.setForeground(new java.awt.Color(255, 255, 255));
        lbl_deleteBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_deleteBook.setText("Delete Book");
        lbl_deleteBook.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_deleteBook.setOpaque(true);
        lbl_deleteBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_deleteBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_deleteBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_deleteBookMouseExited(evt);
            }
        });

        lbl_back.setBackground(new java.awt.Color(153, 153, 153));
        lbl_back.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back.setText("BACK");
        lbl_back.setOpaque(true);
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backMouseReleased(evt);
            }
        });

        lbl_viewReturned.setBackground(new java.awt.Color(58, 63, 67));
        lbl_viewReturned.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_viewReturned.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewReturned.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_viewReturned.setText("View returned Books");
        lbl_viewReturned.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_viewReturned.setOpaque(true);
        lbl_viewReturned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewReturnedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewReturnedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewReturnedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_viewBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_viewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addComponent(lbl_viewIssue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_deleteBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_viewReturned, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lbl_viewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_viewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_viewIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_deleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_viewReturned, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 900));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("—");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("University Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 517, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_addNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_addNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_addNameActionPerformed

    private void tf_copiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_copiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_copiesActionPerformed

    private void tf_addIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addIdFocusGained
        // TODO add your handling code here:
        lbl_bookid.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_addIdFocusGained

    private void tf_addIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addIdFocusLost
        // TODO add your handling code here:
        lbl_bookid.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tf_addIdFocusLost

    private void tf_addNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addNameFocusGained
        // TODO add your handling code here:
        lbl_bookName.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_addNameFocusGained

    private void tf_addNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addNameFocusLost
        // TODO add your handling code here:
        lbl_bookName.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tf_addNameFocusLost

    private void tf_addAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addAuthorFocusGained
        // TODO add your handling code here:\
        lbl_author.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_addAuthorFocusGained

    private void tf_addAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addAuthorFocusLost
        // TODO add your handling code here:
        lbl_author.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tf_addAuthorFocusLost

    private void tf_addEditionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addEditionFocusGained
        // TODO add your handling code here:
          lbl_edition.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_addEditionFocusGained

    private void tf_addEditionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addEditionFocusLost
        // TODO add your handling code here:
          lbl_edition.setForeground(new Color(102,102,102)); 
    }//GEN-LAST:event_tf_addEditionFocusLost

    private void tf_addPublicationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addPublicationFocusGained
        // TODO add your handling code here:
         lbl_publi.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_addPublicationFocusGained

    private void tf_addPublicationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_addPublicationFocusLost
        // TODO add your handling code here:
        lbl_publi.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tf_addPublicationFocusLost

    private void tf_copiesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_copiesFocusGained
        // TODO add your handling code here:
         lbl_copies.setForeground(new Color(56, 125, 232));
    }//GEN-LAST:event_tf_copiesFocusGained

    private void tf_copiesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_copiesFocusLost
        // TODO add your handling code here:
         lbl_copies.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_tf_copiesFocusLost

    private void Lbl_addBooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_addBooksMouseClicked
        // TODO add your handling code here:
             lbl_bookName.setForeground(new Color(102,102,102));
             lbl_edition.setForeground(new Color(102,102,102)); 
             lbl_publi.setForeground(new Color(102,102,102));
             lbl_copies.setForeground(new Color(102,102,102));
             lbl_author.setForeground(new Color(102,102,102));
             lbl_bookid.setForeground(new Color(102,102,102));
             
//          *****************************Adding Books details to Database **********************************

            book_name=tf_addName.getText();
            name_capital= book_name.substring(0,1).toUpperCase()+book_name.substring(1);
             try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
                String sql =  "insert into tp (book_id, name, author_name, publisher, edition , copies) values(?, ?, ?, ?, ?, ?)";
                PreparedStatement st = con.prepareStatement(sql);
                              // st.setInt(1, Integer.parseInt(textField.getText()));
                st.setString(1, tf_addId.getText());
                st.setString(2, name_capital);
                st.setString(3, tf_addAuthor.getText());
                st.setString(4, tf_addPublication.getText());
                st.setString(5,  tf_addEdition.getText());
                st.setString(6,  tf_copies.getText());

                int rs = st.executeUpdate();
                if (rs > 0)
                  JOptionPane.showMessageDialog(null, "Successfully Added");
 
                con.close();
        }catch(Exception e){
            
        }
             
            // **********************resting the textfield to null**************************
            tf_addAuthor.setText("");
            tf_addEdition.setText("");
            tf_addId.setText("");
            tf_addName.setText("");
            tf_addPublication.setText("");
            tf_copies.setText("");
            
             
//             *************************Retrieving data form Database to table***********************
              try
             { 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
            String sql = "SELECT * FROM tp ";
            ps = con.prepareStatement(sql);
            
            rs = ps.executeQuery ();
            DefaultTableModel tblModel = (DefaultTableModel)table.getModel();
            tblModel.setRowCount(0);
            while(rs.next())
            {
                b_id  = rs.getString("book_id");
                b_name = rs.getString("name");
                b_author = rs.getString("author_name");
                b_edition = rs.getString("edition");
                b_publication =  rs.getString("publisher");
                
                 String tbdata[]={b_id,b_name,b_author,b_edition,b_publication,};
                tblModel.addRow(tbdata);
            } 
        }
        catch(Exception e)
        {
                e.getMessage();
        } 
       
    }//GEN-LAST:event_Lbl_addBooksMouseClicked

    private void Lbl_addBooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_addBooksMouseEntered
        // TODO add your handling code here:
        Lbl_addBooks.setBackground(new Color (253,85,85));
        
    }//GEN-LAST:event_Lbl_addBooksMouseEntered

    private void Lbl_addBooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_addBooksMouseExited
        // TODO add your handling code here:
        Lbl_addBooks.setBackground(new Color (113,189,255));
    }//GEN-LAST:event_Lbl_addBooksMouseExited

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        
        this.mouseX = evt.getX();
        this.mouseY = evt.getY();
        
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX,y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel7.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:

        jLabel7.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel8MouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int ans = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit","Close",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:

        lblClose.setBackground(redColor);
        lblClose.setForeground(Color.WHITE);

    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setBackground(Color.WHITE);
        lblClose.setForeground(redColor);

    }//GEN-LAST:event_lblCloseMouseExited

    private void lbl_viewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewBookMouseClicked
        // TODO add your handling code here:
        new Admin_viewBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewBookMouseClicked

    private void lbl_viewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewBookMouseEntered
        // TODO add your handling code here:
        lbl_viewBook.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_viewBookMouseEntered

    private void lbl_viewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewBookMouseExited
        // TODO add your handling code here:
        lbl_viewBook.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_viewBookMouseExited

    private void lbl_viewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewUserMouseClicked
        // TODO add your handling code here:
        new Admin_LibraryViewUsers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewUserMouseClicked

    private void lbl_viewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewUserMouseEntered
        // TODO add your handling code here:
        lbl_viewUser.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_viewUserMouseEntered

    private void lbl_viewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewUserMouseExited
        // TODO add your handling code here:
        lbl_viewUser.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_viewUserMouseExited

    private void lbl_viewIssueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssueMouseClicked
        // TODO add your handling code here:
        new Admin_LibraryIssuedBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewIssueMouseClicked

    private void lbl_viewIssueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssueMouseEntered
        // TODO add your handling code here:
        lbl_viewIssue.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_viewIssueMouseEntered

    private void lbl_viewIssueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssueMouseExited
        // TODO add your handling code here:
        lbl_viewIssue.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_viewIssueMouseExited

    private void lbl_deleteBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_deleteBookMouseClicked
        // TODO add your handling code here:

        new DeleteBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_deleteBookMouseClicked

    private void lbl_deleteBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_deleteBookMouseEntered
        // TODO add your handling code here:
        lbl_deleteBook.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_deleteBookMouseEntered

    private void lbl_deleteBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_deleteBookMouseExited
        // TODO add your handling code here:
        lbl_deleteBook.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_deleteBookMouseExited

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        // TODO add your handling code here:
        //       new Admin_LibraryDashboard().setVisible(true);
        //       this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseEntered
        // TODO add your handling code here:

        lbl_back.setBackground(new Color(255,255,255));
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y-4);
    }//GEN-LAST:event_lbl_backMouseEntered

    private void lbl_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseExited
        // TODO add your handling code here:
        lbl_back.setBackground(new Color(153,153,153));
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y+4);
    }//GEN-LAST:event_lbl_backMouseExited

    private void lbl_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMousePressed
        // TODO add your handling code here:
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y-4);
    }//GEN-LAST:event_lbl_backMousePressed

    private void lbl_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseReleased
        // TODO add your handling code here:
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y+4);
        new Admin_LibraryDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseReleased

    private void lbl_viewReturnedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReturnedMouseClicked
        // TODO add your handling code here:
        new Admin_LibraryReturnBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_viewReturnedMouseClicked

    private void lbl_viewReturnedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReturnedMouseEntered
        // TODO add your handling code here:
        lbl_viewReturned.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_viewReturnedMouseEntered

    private void lbl_viewReturnedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewReturnedMouseExited
        // TODO add your handling code here:
        lbl_viewReturned.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_viewReturnedMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_addBooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_bookid;
    private javax.swing.JLabel lbl_copies;
    private javax.swing.JLabel lbl_deleteBook;
    private javax.swing.JLabel lbl_edition;
    private javax.swing.JLabel lbl_publi;
    private javax.swing.JLabel lbl_viewBook;
    private javax.swing.JLabel lbl_viewIssue;
    private javax.swing.JLabel lbl_viewReturned;
    private javax.swing.JLabel lbl_viewUser;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_addAuthor;
    private javax.swing.JTextField tf_addEdition;
    private javax.swing.JTextField tf_addId;
    private javax.swing.JTextField tf_addName;
    private javax.swing.JTextField tf_addPublication;
    private javax.swing.JTextField tf_copies;
    // End of variables declaration//GEN-END:variables
}
