/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Atharva Dhadke
 */
public class Admin_FeesNotice extends javax.swing.JFrame {

    /**
     * Creates new form Admin_FeesNotice
     */
    public Admin_FeesNotice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_notice = new javax.swing.JTextArea();
        lbl_add = new javax.swing.JLabel();
        lbl_back2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 125, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Notice ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Notice :-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 88, -1, -1));

        ta_notice.setColumns(20);
        ta_notice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ta_notice.setLineWrap(true);
        ta_notice.setRows(5);
        ta_notice.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ta_notice);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 88, 450, 164));

        lbl_add.setBackground(new java.awt.Color(153, 153, 153));
        lbl_add.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add.setText("Add");
        lbl_add.setOpaque(true);
        lbl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_addMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_addMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 270, 113, -1));

        lbl_back2.setBackground(new java.awt.Color(153, 153, 153));
        lbl_back2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_back2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back2.setText("BACK");
        lbl_back2.setOpaque(true);
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_back2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_back2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_back2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_back2MouseReleased(evt);
            }
        });
        getContentPane().add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 270, 102, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        // TODO add your handling code here:
     
        this.dispose();
    }//GEN-LAST:event_lbl_back2MouseClicked

    private void lbl_back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseEntered
        // TODO add your handling code here:

        lbl_back2.setBackground(new Color(255,255,255));
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y-4);
    }//GEN-LAST:event_lbl_back2MouseEntered

    private void lbl_back2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseExited
        // TODO add your handling code here:
        lbl_back2.setBackground(new Color(153,153,153));
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y+4);
    }//GEN-LAST:event_lbl_back2MouseExited

    private void lbl_back2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MousePressed
        // TODO add your handling code here:
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y-4);
    }//GEN-LAST:event_lbl_back2MousePressed

    private void lbl_back2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseReleased
        // TODO add your handling code here:
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y+4);
        
    }//GEN-LAST:event_lbl_back2MouseReleased

    private void lbl_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseEntered
        // TODO add your handling code here:
        lbl_add.setBackground(new Color(255,255,255));
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y-4);
    }//GEN-LAST:event_lbl_addMouseEntered

    private void lbl_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseExited
        // TODO add your handling code here:
           lbl_add.setBackground(new Color(153,153,153));
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y+4);
    }//GEN-LAST:event_lbl_addMouseExited

    private void lbl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseClicked
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
                String sql =  "UPDATE `feesnotice` SET `Notice`= ?";
                PreparedStatement st = con.prepareStatement(sql);
                             
                st.setString(1, ta_notice.getText());
             
                int rs = st.executeUpdate();
                if (rs > 0)
                  JOptionPane.showMessageDialog(null, "Notice Added Successfully ");
 
                con.close();
        }catch(Exception e){
            
        }
        
        ta_notice.setText("");
    }//GEN-LAST:event_lbl_addMouseClicked

    private void lbl_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMousePressed
        // TODO add your handling code here:
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y-4);
    }//GEN-LAST:event_lbl_addMousePressed

    private void lbl_addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseReleased
        // TODO add your handling code here:
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y+4);
    }//GEN-LAST:event_lbl_addMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_FeesNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_FeesNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_FeesNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_FeesNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_FeesNotice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JTextArea ta_notice;
    // End of variables declaration//GEN-END:variables
}
