/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static university.portal.Student_Reg.imagepath;

/**
 *
 * @author Atharva Dhadke
 */
public class Admin_AddAccount extends javax.swing.JFrame {

    /**
     * Creates new form Admin_FeesNotice
     */
    String user , conf_pass,pass;
  
      boolean once;
    public Admin_AddAccount() {
        initComponents();
        
       
       
    }
    
     boolean Validation()
    {     
        user = tf_username.getText();
        pass = tf_password.getText();
        
        conf_pass = tf_conf_pass.getText();
         if(user.trim().isEmpty())
        {
             JOptionPane.showMessageDialog(null, "Please Enter  Username", "Error", JOptionPane.ERROR_MESSAGE);
            tf_username.grabFocus();
            return false;
        }
//         if(pass.trim().isEmpty())
//         {
//             JOptionPane.showMessageDialog(null, "Please Enter  Password", "Error", JOptionPane.ERROR_MESSAGE);
//            tf_password.grabFocus();
//            return false;
//        }
//           if(conf_pass.trim().isEmpty())
//         {
//             JOptionPane.showMessageDialog(null, "Please Enter  Confirm Password", "Error", JOptionPane.ERROR_MESSAGE);
//            tf_conf_pass.grabFocus();
//            return false;
//        }
//          if(!pass.equals( conf_pass))
//        {
//            JOptionPane.showMessageDialog(null, "Password Does not match", "Error", JOptionPane.ERROR_MESSAGE);
//            tf_conf_pass.grabFocus();
//            return false;
//        }
         
         return true;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_add = new javax.swing.JLabel();
        lbl_back2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_conf_pass = new javax.swing.JPasswordField();
        tf_password = new javax.swing.JPasswordField();
        tf_username = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(122, 125, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Account ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 603, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 152, -1, 46));

        lbl_add.setBackground(new java.awt.Color(153, 153, 153));
        lbl_add.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_add.setText("Add");
        lbl_add.setOpaque(true);
        lbl_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_addMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_addMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_addMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 300, 113, -1));

        lbl_back2.setBackground(new java.awt.Color(153, 153, 153));
        lbl_back2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_back2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back2.setText("BACK");
        lbl_back2.setOpaque(true);
        lbl_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_back2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_back2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_back2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_back2MouseReleased(evt);
            }
        });
        getContentPane().add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 102, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel3.setText("Username :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 83, -1, 46));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel4.setText("Confirm Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 218, -1, 46));

        tf_conf_pass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(tf_conf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 224, 256, 42));

        tf_password.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(tf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 158, 359, 42));

        tf_username.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 83, 359, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseClicked
        // TODO add your handling code here:
      
        this.dispose();
    }//GEN-LAST:event_lbl_back2MouseClicked

    private void lbl_back2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseEntered
        // TODO add your handling code here:

        lbl_back2.setBackground(new Color(255,255,255));
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y-4);
    }//GEN-LAST:event_lbl_back2MouseEntered

    private void lbl_back2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseExited
        // TODO add your handling code here:
        lbl_back2.setBackground(new Color(153,153,153));
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y+4);
    }//GEN-LAST:event_lbl_back2MouseExited

    private void lbl_back2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MousePressed
        // TODO add your handling code here:
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y-4);
    }//GEN-LAST:event_lbl_back2MousePressed

    private void lbl_back2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back2MouseReleased
        // TODO add your handling code here:
        lbl_back2.setLocation(lbl_back2.getLocation().x, lbl_back2.getLocation().y+4);
        
    }//GEN-LAST:event_lbl_back2MouseReleased

    private void lbl_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseEntered
        // TODO add your handling code here:
        lbl_add.setBackground(new Color(255,255,255));
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y-4);
    }//GEN-LAST:event_lbl_addMouseEntered

    private void lbl_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseExited
        // TODO add your handling code here:
           lbl_add.setBackground(new Color(153,153,153));
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y+4);
        
    }//GEN-LAST:event_lbl_addMouseExited

    private void lbl_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseClicked
        // TODO add your handling code here:
          user = tf_username.getText();
        pass = tf_password.getText();
        
       conf_pass = tf_conf_pass.getText();
         Validation();
         PreparedStatement ps;
             
        if(tf_password.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter password",  "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else if(tf_password.getText().equals(tf_conf_pass.getText())){
             try{

                   String query ="INSERT INTO `admindb`(`username`,`password`) Values (?,?)";
                   ps = MyConnection.getConnection().prepareStatement(query);

                    ps.setString(1, tf_username.getText());
                    ps.setString(2, pass);
                    System.out.println(pass.length());


                   if(ps.executeUpdate() > 0)
                   {
                       JOptionPane.showMessageDialog(null, "New Admin Account added successfully");
                       
                       this.dispose();
                   }


               } catch(SQLException ex)
               {
       //              Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
               }
            
        }
        else{   
          
            JOptionPane.showMessageDialog(null, "Confirm Password does not match",  "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(tf_password.getText());
            System.out.println(tf_conf_pass.getText());
        }
  
    }//GEN-LAST:event_lbl_addMouseClicked

    private void lbl_addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMousePressed
        // TODO add your handling code here:
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y-4);
    }//GEN-LAST:event_lbl_addMousePressed

    private void lbl_addMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_addMouseReleased
        // TODO add your handling code here:
        lbl_add.setLocation(lbl_add.getLocation().x, lbl_add.getLocation().y+4);
    }//GEN-LAST:event_lbl_addMouseReleased

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_AddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_AddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_add;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JPasswordField tf_conf_pass;
    private javax.swing.JPasswordField tf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
