 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;


import java.awt.Color;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Atharva
 */
public class Student_Login extends javax.swing.JFrame {

    /**
     * Creates new form Student_Login
     */
    static String username;
    private int mouseX;
    private int mouseY;
    private Color redColor = new Color(204,51,0);
    
    public Student_Login() {
        initComponents();
    }
    
    void User_Verification(String username , String password)
    {
        try
        {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
           
            String sql ="select * from  studentdb where username = ? and Password = ?";
            
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,username);
            pst.setString(2,password);
            ResultSet rs=pst.executeQuery();
            if(rs.next())
            {
            Student_Dashboard home = new Student_Dashboard();
            home.show();
            this.dispose();
            }
            
            else
            {
                JOptionPane.showMessageDialog(this , "Wrong Username and Password");
            }
        }
    
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pnl_Header = new javax.swing.JPanel();
        Lbl_University_Logo = new javax.swing.JLabel();
        Lbl_UniversityName = new javax.swing.JLabel();
        Lbl_PortalName = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pnl_Left = new javax.swing.JPanel();
        Lbl_StudentLogo = new javax.swing.JLabel();
        Lbl_StudentloginNAme = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Pnl_Right = new javax.swing.JPanel();
        Lbl_SigninName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Lbl_Password = new javax.swing.JLabel();
        tf_StdUsername = new javax.swing.JTextField();
        tf_StdPassword = new javax.swing.JPasswordField();
        Btn_StdLogin = new javax.swing.JButton();
        Btn_StdRegister = new javax.swing.JButton();
        Lbl_LogoUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_Loginerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pnl_Header.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Pnl_Header.setPreferredSize(new java.awt.Dimension(1600, 65));
        Pnl_Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Pnl_HeaderMouseDragged(evt);
            }
        });
        Pnl_Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Pnl_HeaderMousePressed(evt);
            }
        });
        Pnl_Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_University_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/MAINPAINT-removebg-preview.png"))); // NOI18N
        Pnl_Header.add(Lbl_University_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 73));

        Lbl_UniversityName.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Lbl_UniversityName.setForeground(new java.awt.Color(220, 41, 62));
        Lbl_UniversityName.setText("University");
        Pnl_Header.add(Lbl_UniversityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 13, -1, 47));

        Lbl_PortalName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 42)); // NOI18N
        Lbl_PortalName.setForeground(new java.awt.Color(152, 32, 82));
        Lbl_PortalName.setText("University Portal");
        Pnl_Header.add(Lbl_PortalName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 330, 50));

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        Pnl_Header.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 0, 70, 60));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("—");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        Pnl_Header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 0, 70, 60));

        getContentPane().add(Pnl_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Pnl_Left.setBackground(new java.awt.Color(0, 165, 207));
        Pnl_Left.setPreferredSize(new java.awt.Dimension(800, 790));
        Pnl_Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_StudentLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/Logo_Student.png"))); // NOI18N
        Pnl_Left.add(Lbl_StudentLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 540, 600));

        Lbl_StudentloginNAme.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        Lbl_StudentloginNAme.setText("Student Login");
        Pnl_Left.add(Lbl_StudentloginNAme, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 320, 60));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        Pnl_Left.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 370, 10));

        getContentPane().add(Pnl_Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 830));

        Pnl_Right.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_SigninName.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        Lbl_SigninName.setForeground(new java.awt.Color(0, 0, 153));
        Lbl_SigninName.setText("Sign In");
        Pnl_Right.add(Lbl_SigninName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setText("Username :");
        Pnl_Right.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        Lbl_Password.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        Lbl_Password.setText("Password :");
        Pnl_Right.add(Lbl_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        tf_StdUsername.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        tf_StdUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_StdUsernameActionPerformed(evt);
            }
        });
        Pnl_Right.add(tf_StdUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 250, 50));

        tf_StdPassword.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Pnl_Right.add(tf_StdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 250, 50));

        Btn_StdLogin.setBackground(new java.awt.Color(6, 135, 246));
        Btn_StdLogin.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Btn_StdLogin.setForeground(new java.awt.Color(255, 255, 255));
        Btn_StdLogin.setText("Login");
        Btn_StdLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StdLoginActionPerformed(evt);
            }
        });
        Pnl_Right.add(Btn_StdLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 200, 70));

        Btn_StdRegister.setBackground(new java.awt.Color(253, 85, 85));
        Btn_StdRegister.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Btn_StdRegister.setText("Register");
        Btn_StdRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_StdRegisterActionPerformed(evt);
            }
        });
        Pnl_Right.add(Btn_StdRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 200, 70));

        Lbl_LogoUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/Username_Logo.png"))); // NOI18N
        Pnl_Right.add(Lbl_LogoUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/university/portal/Password.logo.png"))); // NOI18N
        Pnl_Right.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 80, 80));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 51));
        Pnl_Right.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 230, -1));

        lbl_Loginerror.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Loginerror.setForeground(new java.awt.Color(255, 0, 0));
        Pnl_Right.add(lbl_Loginerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 450, 30));

        getContentPane().add(Pnl_Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 980, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_StdRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StdRegisterActionPerformed
        // TODO add your handling code here:
        new Student_Reg().setVisible(true);
    }//GEN-LAST:event_Btn_StdRegisterActionPerformed

    private void Btn_StdLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_StdLoginActionPerformed
        // TODO add your handling code here:
        username = tf_StdUsername.getText();
         String password = tf_StdPassword.getText();
         
         if(username.trim().equals("") || password.trim().equals(""))
         {
             lbl_Loginerror.setText("Please Enter Username and Password!");
         }
         else
         {
             User_Verification(username , password);
             
         }
    }//GEN-LAST:event_Btn_StdLoginActionPerformed

    private void tf_StdUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_StdUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_StdUsernameActionPerformed

    private void Pnl_HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pnl_HeaderMousePressed
        // TODO add your handling code here:
        
        this.mouseX = evt.getX();
        this.mouseY = evt.getY();

    }//GEN-LAST:event_Pnl_HeaderMousePressed

    private void Pnl_HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pnl_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX,y - mouseY);
    }//GEN-LAST:event_Pnl_HeaderMouseDragged

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int ans = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit","Close",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:

        lblClose.setBackground(redColor);
        lblClose.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setBackground(Color.WHITE);
        lblClose.setForeground(redColor);
        

    }//GEN-LAST:event_lblCloseMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:

        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:

        jLabel7.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_StdLogin;
    private javax.swing.JButton Btn_StdRegister;
    private javax.swing.JLabel Lbl_LogoUsername;
    private javax.swing.JLabel Lbl_Password;
    private javax.swing.JLabel Lbl_PortalName;
    private javax.swing.JLabel Lbl_SigninName;
    private javax.swing.JLabel Lbl_StudentLogo;
    private javax.swing.JLabel Lbl_StudentloginNAme;
    private javax.swing.JLabel Lbl_UniversityName;
    private javax.swing.JLabel Lbl_University_Logo;
    private javax.swing.JPanel Pnl_Header;
    private javax.swing.JPanel Pnl_Left;
    private javax.swing.JPanel Pnl_Right;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lbl_Loginerror;
    private javax.swing.JPasswordField tf_StdPassword;
    private javax.swing.JTextField tf_StdUsername;
    // End of variables declaration//GEN-END:variables
}
