/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package university.portal;

import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import static university.portal.Student_Dashboard.ret_enroll;
import static university.portal.Student_Dashboard.ret_fname;
import static university.portal.Student_Dashboard.ret_lname;



/**
 *
 * @author Atharva Dhadke
 */
public class Student_ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form Student_IssueBook
     */

   String b_id,b_name,b_author,b_publication,b_edition, bdate,issuedate ;
   
   String i_username = Student_Dashboard.ret_username;
    String compare;
    String bookid;
     int copies;
     long days;
    String copy;
   PreparedStatement ps;
    Connection con ;
    ResultSet rs;
    String returndate;
    
     private int mouseX;
    private int mouseY;
    private Color redColor = new Color(204,51,0); 
    
    public Student_ReturnBook() {
        initComponents();
        
         lbl_username.setText(FirstPage.username);
        
          JTableHeader Theader = table.getTableHeader();
        Theader.setFont(new Font("Tahome " ,Font.BOLD, 20));
        
       
        
         table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 20));
          table.getTableHeader().setOpaque(false);
          table.getTableHeader().setBackground(new Color(58, 63, 67));
          table.getTableHeader().setForeground(new Color(255,255,255));
          
        
          try
        { 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
            String sql = "SELECT * FROM issuedetails where username='" + i_username + "'";
            ps = con.prepareStatement(sql);
            
            rs = ps.executeQuery ();
            DefaultTableModel tblModel = (DefaultTableModel)table.getModel();
             tblModel = (DefaultTableModel)table.getModel();
             tblModel.setRowCount(0);
            while(rs.next())
            {
                b_id  = rs.getString("book_id");
                b_name = rs.getString("name");
                b_author = rs.getString("author_name");
                b_edition = rs.getString("edition");
                b_publication =  rs.getString("publisher");
                bdate=rs.getString("issuedate");
                
                String tbdata[] ={b_id,b_name,b_author,b_edition,b_publication,bdate};
                tblModel.addRow(tbdata);
                
                
            } 
        }
        catch(Exception e)
        {
                e.getMessage();
        } 
          
          Date selectedDate = new Date(); //jDateChooser1.getDate();
         SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
         returndate = dateformat.format(selectedDate);
         
         lbl_returndate.setText(returndate);
         
         
         
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_leftView = new javax.swing.JLabel();
        left_leftissue = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_bookId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_edition = new javax.swing.JLabel();
        lbl_publisher = new javax.swing.JLabel();
        lbl_DOI = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_returndate = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbl_back1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 850));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(58, 63, 67));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 850));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Atharva Dhadke\\Desktop\\Java Project Images\\final admin .png")); // NOI18N
        jLabel19.setText("jLabel19");

        lbl_username.setBackground(new java.awt.Color(0, 0, 0));
        lbl_username.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_username.setOpaque(true);

        lbl_leftView.setBackground(new java.awt.Color(58, 63, 67));
        lbl_leftView.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_leftView.setForeground(new java.awt.Color(255, 255, 255));
        lbl_leftView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_leftView.setText("View Books");
        lbl_leftView.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        lbl_leftView.setOpaque(true);
        lbl_leftView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_leftViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_leftViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_leftViewMouseExited(evt);
            }
        });

        left_leftissue.setBackground(new java.awt.Color(58, 63, 67));
        left_leftissue.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        left_leftissue.setForeground(new java.awt.Color(255, 255, 255));
        left_leftissue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        left_leftissue.setText("Issue Books");
        left_leftissue.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(74, 81, 86)));
        left_leftissue.setOpaque(true);
        left_leftissue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                left_leftissueMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                left_leftissueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                left_leftissueMouseExited(evt);
            }
        });

        lbl_back.setBackground(new java.awt.Color(153, 153, 153));
        lbl_back.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back.setText("BACK");
        lbl_back.setOpaque(true);
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_backMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_backMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_leftView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(left_leftissue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(lbl_leftView, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(left_leftissue, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 900));

        jPanel3.setBackground(new java.awt.Color(122, 125, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Book");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(463, 463, 463)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(506, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 1240, 70));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author Name", "Edition", "Publication", "Issue Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setRowHeight(30);
        table.setRowMargin(5);
        table.setSelectionBackground(new java.awt.Color(255, 102, 102));
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(85);
            table.getColumnModel().getColumn(0).setPreferredWidth(85);
            table.getColumnModel().getColumn(0).setMaxWidth(85);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setMinWidth(240);
            table.getColumnModel().getColumn(2).setPreferredWidth(240);
            table.getColumnModel().getColumn(2).setMaxWidth(240);
            table.getColumnModel().getColumn(3).setMinWidth(90);
            table.getColumnModel().getColumn(3).setPreferredWidth(90);
            table.getColumnModel().getColumn(3).setMaxWidth(90);
            table.getColumnModel().getColumn(4).setMinWidth(230);
            table.getColumnModel().getColumn(4).setPreferredWidth(230);
            table.getColumnModel().getColumn(4).setMaxWidth(230);
            table.getColumnModel().getColumn(5).setMinWidth(120);
            table.getColumnModel().getColumn(5).setPreferredWidth(120);
            table.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 180));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel2.setText("Book Id :");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 46, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel3.setText("Book Name :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 124, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel4.setText("Author Name :");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 193, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel5.setText("Edition :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 263, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel6.setText("Publisher :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 334, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        jLabel9.setText("Date of Issue :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 384, -1, 31));

        lbl_bookId.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_bookId.setText(" ");
        jPanel4.add(lbl_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 46, 384, -1));

        lbl_bookName.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_bookName.setText(" ");
        jPanel4.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 124, 384, -1));

        lbl_author.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_author.setText(" ");
        jPanel4.add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 193, 384, -1));

        lbl_edition.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_edition.setText(" ");
        jPanel4.add(lbl_edition, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 263, 384, -1));

        lbl_publisher.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_publisher.setText(" ");
        jPanel4.add(lbl_publisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 334, 384, -1));

        lbl_DOI.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        lbl_DOI.setText(" ");
        jPanel4.add(lbl_DOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 384, 384, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setText("Return Date :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, -1, -1));

        lbl_returndate.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel4.add(lbl_returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, 190, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("All CopyRights Reserved /University");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 290, -1));

        lbl_back1.setBackground(new java.awt.Color(153, 153, 153));
        lbl_back1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbl_back1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back1.setText("Return Book ");
        lbl_back1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_back1.setOpaque(true);
        lbl_back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_back1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_back1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_back1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_back1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_back1MouseReleased(evt);
            }
        });
        jPanel4.add(lbl_back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 220, 60));

        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1240, 530));

        jPanel8.setBackground(new java.awt.Color(122, 125, 128));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Book Details");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1240, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 1240, 780));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("—");
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        lblClose.setBackground(new java.awt.Color(255, 255, 255));
        lblClose.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 0, 0));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("University Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 499, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                    .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
//         JTable source = (JTable)evt.getSource();
//            int row = source.rowAtPoint( evt.getPoint() );
//            int column = source.columnAtPoint( evt.getPoint() );
//            String s=source.getModel().getValueAt(row, column)+"";
//
//            JOptionPane.showMessageDialog(null, s);

            
            int selectedRow = table.getSelectedRow();
            bookid = table.getValueAt(selectedRow, 0).toString();
            String bookname = table.getValueAt(selectedRow, 1).toString();
            String authorname = table.getValueAt(selectedRow, 2).toString();
            String edition = table.getValueAt(selectedRow, 3).toString();
            String publication = table.getValueAt(selectedRow, 4).toString();
             issuedate = table.getValueAt(selectedRow, 5).toString();
            
        
    
//        System.out.println(bookid);
//        System.out.println(bookname);
//        System.out.println(authorname);
//        System.out.println(edition);
//        System.out.println(publication);
//        System.out.println(issuedate);
        
        lbl_bookId.setText(bookid);
        lbl_bookName.setText(bookname);
        lbl_author.setText(authorname);
        lbl_edition.setText(edition);
        lbl_publisher.setText(publication);
        lbl_DOI.setText(issuedate);
        
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
       
        try {
            Date date1 = myFormat.parse(issuedate);
            Date date2 = myFormat.parse(returndate);
            long diff = date2.getTime() - date1.getTime();
            days = TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
            System.out.println ("Days: "+days);
        } catch (Exception e) {
            e.getMessage();
        }


        
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:

        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setBackground(new Color(229,229,229));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:

        jLabel14.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jLabel14MouseExited

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int ans = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit","Close",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:

        lblClose.setBackground(redColor);
        lblClose.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        lblClose.setBackground(Color.WHITE);
        lblClose.setForeground(redColor);
    }//GEN-LAST:event_lblCloseMouseExited

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX,y - mouseY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:

        this.mouseX = evt.getX();
        this.mouseY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void lbl_leftViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_leftViewMouseClicked
        // TODO add your handling code here:
        new Student_ViewBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_leftViewMouseClicked

    private void lbl_leftViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_leftViewMouseEntered
        // TODO add your handling code here:
        lbl_leftView.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_lbl_leftViewMouseEntered

    private void lbl_leftViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_leftViewMouseExited
        // TODO add your handling code here:
        lbl_leftView.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_lbl_leftViewMouseExited

    private void left_leftissueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_left_leftissueMouseClicked
        // TODO add your handling code here:
        new Student_IssueBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_left_leftissueMouseClicked

    private void left_leftissueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_left_leftissueMouseEntered
        // TODO add your handling code here:
        left_leftissue.setBackground(new Color(78, 85, 90));
    }//GEN-LAST:event_left_leftissueMouseEntered

    private void left_leftissueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_left_leftissueMouseExited
        // TODO add your handling code here:
        left_leftissue.setBackground(new Color(58,63,67));
    }//GEN-LAST:event_left_leftissueMouseExited

    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        // TODO add your handling code here:
        //               new Admin_LibraryDashboard().setVisible(true);
        //               this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void lbl_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseEntered
        // TODO add your handling code here:

        lbl_back.setBackground(new Color(255,255,255));
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y-4);
    }//GEN-LAST:event_lbl_backMouseEntered

    private void lbl_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseExited
        // TODO add your handling code here:
        lbl_back.setBackground(new Color(153,153,153));
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y+4);
    }//GEN-LAST:event_lbl_backMouseExited

    private void lbl_backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMousePressed
        // TODO add your handling code here:
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y-4);
    }//GEN-LAST:event_lbl_backMousePressed

    private void lbl_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseReleased
        // TODO add your handling code here:
        lbl_back.setLocation(lbl_back.getLocation().x, lbl_back.getLocation().y+4);
       new Library_Dashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseReleased

    private void lbl_back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MouseClicked
        // TODO add your handling code here:
        
         String str_fine ="0";
         long fine= 0;
        compare = i_username +"-"+ bookid;
        
        if(days > 7) {
            JOptionPane.showMessageDialog(null, "Return Date Expired ");
            
            fine = (days - 7) *10;   
            long latedays  = (days - 7);
            
            str_fine = String.valueOf(fine);
            
            
            if(latedays == 1){
             JOptionPane.showMessageDialog(null, "Your fine for "+latedays+" Day is "+fine+" Rs  Please pay the amount to librarian");
            }
            else{
                 JOptionPane.showMessageDialog(null, "Your fine for "+latedays+" Days is "+fine+" Rs Please pay the amount to librarian");
            }
        }
        
         /************************** Delete's issued book record from database******************/   
        try{
                  System.out.println(" Delete's issued book record from database");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            PreparedStatement ps;
         
               
                String sql = " DELETE FROM `issuedetails` WHERE `usernamebookid` ='" +compare +"'";
        
            
             ps = con.prepareStatement(sql);
                         
            if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "You have returned the book ");
            }
            else{
                System.out.print("Book not inserted!!!") ;
            }   
        } catch(Exception ex){
            ex.getMessage();
        }
     /************************** Display's table after returning book******************/   
         try
        { 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
            String sql = "SELECT * FROM issuedetails where username='" + i_username + "'";
            ps = con.prepareStatement(sql);
            
            rs = ps.executeQuery ();
            DefaultTableModel tblModel = (DefaultTableModel)table.getModel();
             tblModel = (DefaultTableModel)table.getModel();
             tblModel.setRowCount(0);
            while(rs.next())
            {
                b_id  = rs.getString("book_id");
                b_name = rs.getString("name");
                b_author = rs.getString("author_name");
                b_edition = rs.getString("edition");
                b_publication =  rs.getString("publisher");
                bdate=rs.getString("issuedate");
                
                String tbdata[] ={b_id,b_name,b_author,b_edition,b_publication,bdate};
                tblModel.addRow(tbdata);
                
                
            } 
        }
        catch(Exception e)
        {
                e.getMessage();
        } 
         
        /************************** Getting quantity of books available ******************/ 
        try
             { 
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
            
            String sql = "SELECT * FROM tp where `book_id` ='"+bookid+"'";
            ps = con.prepareStatement(sql);
            
            rs = ps.executeQuery ();
     
            while(rs.next())
            {
                copy=rs.getString("copies");            
            } 
            con.close();
           
        }
        catch(Exception e)
        {
                e.getMessage();
        } 
            
          System.out.println(copy);
          copies=Integer.parseInt(copy);
          
          copies= copies+1;
          
          /************************** Incrementing book count after Returning ******************/  
          try{
                 System.out.println("Incrementing book count after Returning");
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
                       PreparedStatement ps;

                        String sql =  "UPDATE `tp` SET `copies` =? WHERE book_id = '"+bookid+"'";
//                           String sql = " UPDATE `tp` SET `copies`= ? WHERE book_id = '8' ";

                       ps = con.prepareStatement(sql);

                         ps.setInt(1,copies);
                        

                       if(ps.executeUpdate() > 0){
//                           JOptionPane.showMessageDialog(null, "Book incremented ");
                       }
                       else {
                       System.out.print("Count is not incrementing!") ;
                       }   
            }
        catch(Exception ex){
         ex.getMessage();
        }
          
        /************************** Maintaining databse of users who returned the book ******************/  
          try{
                 System.out.println("entered into Databe Iamintain");
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitydb","AtharvaDhadke","Atharva");
                       PreparedStatement ps;

                        String sql =  "INSERT INTO `returnedbooks`(`book_id`, `book_name`, `student_name`, `enroll`, `issue`, `return`, `fine`) VALUES (?,?,?,?,?,?,?)";
//                           String sql = " UPDATE `tp` SET `copies`= ? WHERE book_id = '8' ";

                       ps = con.prepareStatement(sql);
                       
                       
                       
                        ps.setString(1,b_id);
                        ps.setString(2,b_name);
                        ps.setString(3,ret_fname+" "+ret_lname);
                        ps.setString(4,ret_enroll);
                        ps.setString(5,issuedate);
                        ps.setString(6,returndate);
                        ps.setString(7,str_fine);
                        

                       if(ps.executeUpdate() > 0){
//                           JOptionPane.showMessageDialog(null, "Database Maintained ");
                       }
                       else {
                       System.out.print("Count is not incrementing!") ;
                       }   
            }
        catch(Exception ex){
         ex.getMessage();
        }  
          
        
          
          
          
    
          lbl_bookId.setText("");
        lbl_bookName.setText("");
        lbl_author.setText("");
        lbl_edition.setText("");
        lbl_publisher.setText("");
        lbl_DOI.setText("");    
        

       
    }//GEN-LAST:event_lbl_back1MouseClicked

    private void lbl_back1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MouseEntered
        // TODO add your handling code here:
        lbl_back1.setBackground(new Color(255,255,255));
        lbl_back1.setLocation(lbl_back1.getLocation().x, lbl_back1.getLocation().y-4);

    }//GEN-LAST:event_lbl_back1MouseEntered

    private void lbl_back1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MouseExited
        // TODO add your handling code here:
        lbl_back1.setBackground(new Color(153,153,153));
        lbl_back1.setLocation(lbl_back1.getLocation().x, lbl_back1.getLocation().y+4);
    }//GEN-LAST:event_lbl_back1MouseExited

    private void lbl_back1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MousePressed
        // TODO add your handling code here:
        lbl_back1.setLocation(lbl_back1.getLocation().x, lbl_back1.getLocation().y-4);
    }//GEN-LAST:event_lbl_back1MousePressed

    private void lbl_back1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_back1MouseReleased
        // TODO add your handling code here:
        lbl_back1.setLocation(lbl_back1.getLocation().x, lbl_back1.getLocation().y+4);
    }//GEN-LAST:event_lbl_back1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lbl_DOI;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_back1;
    private javax.swing.JLabel lbl_bookId;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_edition;
    private javax.swing.JLabel lbl_leftView;
    private javax.swing.JLabel lbl_publisher;
    private javax.swing.JLabel lbl_returndate;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel left_leftissue;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
